# Generated by Django 3.0.2 on 2020-05-18 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_document_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
