# Generated by Django 3.0.2 on 2020-05-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_remove_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='bucket',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
