# Generated by Django 3.0.2 on 2020-05-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_folder_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='bucket',
        ),
    ]
