# Generated by Django 3.0.2 on 2020-05-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_remove_folder_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
