# Generated by Django 3.0.2 on 2020-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200521_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarypost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
